name: demoelk

volumes:
  elasticsearch-data:
  kibana-data:

networks:
  app-network:
    driver: bridge

services:
  elk.elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.23
    container_name: elk.elasticsearch
    restart: always
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      app-network:

  elk.kibana:
    image: docker.elastic.co/kibana/kibana:7.17.23
    container_name: elk.kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elk.elasticsearch:9200
    ports:
      - "5601:5601"
    restart: always
    volumes:
      - kibana-data:/usr/share/kibana/data
    depends_on:
      - elk.elasticsearch
    networks:
      app-network:
